Add docs for Liquid drain and list payments details
breez/breez-sdk-liquid-docs pull request #50
Opened 2024-11-12 14:31 UTC by dangeross

This PR:
- bumps SDK version to 0.5.0-rc4
- adds docs for preparing a draining when sending a Liquid payment
- adds docs for listing payments using the Bitcoin address or Liquid destination

2024-11-22 14:49 UTC, ok300 approved these changes
LGTM.

All CI issues are fixed here: #51

2024-11-26 14:57 UTC, roeierez requested changes

2024-11-26 14:57 UTC, roeierez commented on snippets/dart_snippets/lib/send_payment.dart
> +  BigInt optionalAmount = PayAmount_Drain(),
Should be changed to enum?

2024-11-26 16:29 UTC, dangeross commented on snippets/dart_snippets/lib/send_payment.dart
> +  BigInt optionalAmount = PayAmount_Drain(),
Fixed by @ok300's PR

2024-11-26 16:29 UTC, merged